### ISSUE TITLE
setup.py error in Ubuntu 14 and OSX: atexit._run_exitfuncs:

### ISSUE THREAD

**Issue by andrewrech** [hammerlab/mhcflurry#28]
I get the follow error running setup.py on latest OSX and Ubuntu 14

``` shell
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 27, in clean_up_temporary_directory
    for d in _tmpdirs:
TypeError: 'NoneType' object is not iterable
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 27, in clean_up_temporary_directory
    for d in _tmpdirs:
TypeError: 'NoneType' object is not iterable
```

**Comment by timodonnell** [comment]
Hey @andrewrech , apologies for the late reply. We've redone much of this project recently. Can you see if you are still hitting this?

Thanks,

Tim

**Comment by andrewrech** [comment]
Hi Tim,

I am just getting back to this. Looking forward to playing with this in our pipeline.

Andrew
