### ISSUE TITLE
mhcflurry-train-class1-allele-specific-models.py

### ISSUE THREAD

**Issue by jetskiphil** [hammerlab/mhcflurry#32]
I am having trouble running mhcflurry-train-class1-allele-specific-models.py – i get the following error 

[kffw870@ukapdwlx321 script]$ ./mhcflurry-train-class1-allele-specific-models.py
Using Theano backend.
Traceback (most recent call last):
  File "./mhcflurry-train-class1-allele-specific-models.py", line 162, in <module>
    verbose=True)
  File "/apps/mhc/mhcflurry/mhcflurry/class1_allele_specific_kmer_ic50_predictor_base.py", line 187, in fit_dataset
    allow_unknown_amino_acids=self.allow_unknown_amino_acids)
  File "/apps/mhc/mhcflurry/mhcflurry/dataset.py", line 511, in kmer_index_encoding
    allow_unknown_amino_acids=allow_unknown_amino_acids)
  File "/apps/mhc/mhcflurry/mhcflurry/peptide_encoding.py", line 301, in fixed_length_index_encoding
    X = index_encoding(fixed_length, desired_length)
  File "/apps/mhc/mhcflurry/mhcflurry/amino_acid.py", line 75, in index_encoding
    X[i, j] = index_dict[amino_acid]
KeyError: '+'

**Comment by timodonnell** [comment]
Hey @jetskiphil sorry for the late reply. We've changed things now so users no longer have to run this script. I'm going to close this ticket for now but please reopen it if you need to run this script and are still hitting this issue. Also please feel free to file any other issues you hit using the updated mhcflurry, we will hopefully get back to you sooner in the future about any issues.

Thanks,

Tim
