### ISSUE TITLE
Nosetests fail

### ISSUE THREAD

**Issue by maximz** [hammerlab/mhcflurry#35]
Version info:
```
Keras==1.0.5
Theano==0.8.2
```

I ran:
```
script/download-iedb.sh
script/download-kim-2013-dataset.sh
script/create-iedb-class1-dataset.py
script/create-combined-class1-dataset.py
script/mhcflurry-train-class1-allele-specific-models.py # train a model
nosetests .
```

Error is:
```
> nosetests .
Using Theano backend.
.................F.................F.....
======================================================================
FAIL: test_known_class1_epitopes.test_A1_Titin_epitope
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/root/mhcflurry/test/test_known_class1_epitopes.py", line 27, in test_A1_Titin_epitope
    assert ic50 <= 500, ic50
AssertionError: 865.832290779
-------------------- >> begin captured stdout << ---------------------
[ 865.83229078]

--------------------- >> end captured stdout << ----------------------

======================================================================
FAIL: test_predict.test_predict_A1_Titin_epitope
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/root/mhcflurry/test/test_predict.py", line 8, in test_predict_A1_Titin_epitope
    assert ic50 <= 500
AssertionError

----------------------------------------------------------------------
Ran 41 tests in 21.024s

FAILED (failures=2)
```

**Comment by timodonnell** [comment]
this should be fixed now, please reopen if not
