### ISSUE TITLE
README mhcflurry-predict command is broken

### ISSUE THREAD

**Issue by wwang-nmdp** [hammerlab/mhcflurry#67]
```
L0504656:mhcflurry wwang$ 
L0504656:mhcflurry wwang$ mhcflurry-predict --alleles HLA-A0201 HLA-A0301 --peptides SIINFEKL SIINFEKD SIINFEKQ
Using Theano backend.
Predicting for 2 alleles and 3 peptides = 6 predictions
Traceback (most recent call last):
  File "//anaconda/bin/mhcflurry-predict", line 11, in <module>
    load_entry_point('mhcflurry', 'console_scripts', 'mhcflurry-predict')()
  File "/Users/wwang/Documents/Tools/mhcflurry/mhcflurry/predict_command.py", line 142, in run
    model = class1_allele_specific_loader.from_allele_name(allele)
  File "/Users/wwang/Documents/Tools/mhcflurry/mhcflurry/class1_allele_specific/load.py", line 125, in from_allele_name
    self.predictors_cache[allele_name] = pickle.load(fd)
  File "/Users/wwang/Documents/Tools/mhcflurry/mhcflurry/class1_allele_specific/class1_binding_predictor.py", line 132, in __setstate__
    self.model = keras.models.load_model(fd.name)
  File "//anaconda/lib/python3.5/site-packages/keras/models.py", line 167, in load_model
    model.optimizer.set_weights(optimizer_weight_values)
  File "//anaconda/lib/python3.5/site-packages/keras/optimizers.py", line 97, in set_weights
    'provided weight shape ' + str(w.shape))
Exception: Optimizer weight shape (72, 64) not compatible with provided weight shape (64,)
L0504656:mhcflurry wwang$

**Comment by timodonnell** [comment]
My hunch is this is due to keras changing constantly. We should probably pin the keras version.

**Comment by timodonnell** [comment]
Confirmed broken by re-running travis build on master: https://travis-ci.org/hammerlab/mhcflurry/jobs/162961786
