### ISSUE TITLE
Weird error message when installling. 

### ISSUE THREAD

**Issue by alexanderwhatley** [hammerlab/mhcflurry#77]
Platform: Ubuntu 16.04, Windows Linux Subsystem

I got the following error message when downloading the training data:

```
alex@AlexanderPC:/mnt/c/Users/Alexander$ mhcflurry-downloads fetch
Using Theano backend.
Traceback (most recent call last):
  File "/home/alex/anaconda3/bin/mhcflurry-downloads", line 7, in <module>
    from mhcflurry.downloads_command import run
  File "/home/alex/anaconda3/lib/python3.5/site-packages/mhcflurry/__init__.py", line 15, in <module>
    from .class1_allele_specific.class1_binding_predictor import (
  File "/home/alex/anaconda3/lib/python3.5/site-packages/mhcflurry/class1_allele_specific/__init__.py", line 3, in <module>
    from .class1_binding_predictor import Class1BindingPredictor
  File "/home/alex/anaconda3/lib/python3.5/site-packages/mhcflurry/class1_allele_specific/class1_binding_predictor.py", line 32, in <module>
    from .class1_allele_specific_kmer_ic50_predictor_base import (
  File "/home/alex/anaconda3/lib/python3.5/site-packages/mhcflurry/class1_allele_specific/class1_allele_specific_kmer_ic50_predictor_base.py", line 31, in <module>
    from ..ic50_predictor_base import IC50PredictorBase
  File "/home/alex/anaconda3/lib/python3.5/site-packages/mhcflurry/ic50_predictor_base.py", line 24, in <module>
    from .dataset import Dataset
  File "/home/alex/anaconda3/lib/python3.5/site-packages/mhcflurry/dataset.py", line 32, in <module>
    from .imputation_helpers import (
  File "/home/alex/anaconda3/lib/python3.5/site-packages/mhcflurry/imputation_helpers.py", line 23, in <module>
    from fancyimpute.knn import KNN
  File "/home/alex/anaconda3/lib/python3.5/site-packages/fancyimpute/__init__.py", line 4, in <module>
    from .nuclear_norm_minimization import NuclearNormMinimization
  File "/home/alex/anaconda3/lib/python3.5/site-packages/fancyimpute/nuclear_norm_minimization.py", line 15, in <module>
    import cvxpy
  File "/home/alex/anaconda3/lib/python3.5/site-packages/cvxpy/__init__.py", line 21, in <module>
    from cvxpy.atoms import *
  File "/home/alex/anaconda3/lib/python3.5/site-packages/cvxpy/atoms/__init__.py", line 20, in <module>
    from cvxpy.atoms.affine_prod import affine_prod
  File "/home/alex/anaconda3/lib/python3.5/site-packages/cvxpy/atoms/affine_prod.py", line 20, in <module>
    from cvxpy.atoms.atom import Atom
  File "/home/alex/anaconda3/lib/python3.5/site-packages/cvxpy/atoms/atom.py", line 21, in <module>
    from .. import utilities as u
  File "/home/alex/anaconda3/lib/python3.5/site-packages/cvxpy/utilities/__init__.py", line 24, in <module>
    from .quadratic import QuadCoeffExtractor
  File "/home/alex/anaconda3/lib/python3.5/site-packages/cvxpy/utilities/quadratic.py", line 24, in <module>
    import canonInterface
  File "/home/alex/anaconda3/lib/python3.5/site-packages/canonInterface.py", line 16, in <module>
    import CVXcanon
  File "/home/alex/anaconda3/lib/python3.5/site-packages/CVXcanon.py", line 28, in <module>
    _CVXcanon = swig_import_helper()
  File "/home/alex/anaconda3/lib/python3.5/site-packages/CVXcanon.py", line 24, in swig_import_helper
    _mod = imp.load_module('_CVXcanon', fp, pathname, description)
  File "/home/alex/anaconda3/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/alex/anaconda3/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /home/alex/anaconda3/lib/python3.5/site-packages/_CVXcanon.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev
```

**Comment by alexanderwhatley** [comment]
I'm getting the exact same error message on native Ubuntu 16.10 as well:

alexander@alexander-HP-ENVY-m7-Notebook-PC:~$ mhcflurry-downloads fetch
Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "/home/alexander/anaconda3/bin/mhcflurry-downloads", line 7, in <module>
    from mhcflurry.downloads_command import run
  File "/home/alexander/anaconda3/lib/python3.5/site-packages/mhcflurry/__init__.py", line 15, in <module>
    from .class1_allele_specific.class1_binding_predictor import (
  File "/home/alexander/anaconda3/lib/python3.5/site-packages/mhcflurry/class1_allele_specific/__init__.py", line 3, in <module>
    from .class1_binding_predictor import Class1BindingPredictor
  File "/home/alexander/anaconda3/lib/python3.5/site-packages/mhcflurry/class1_allele_specific/class1_binding_predictor.py", line 32, in <module>
    from .class1_allele_specific_kmer_ic50_predictor_base import (
  File "/home/alexander/anaconda3/lib/python3.5/site-packages/mhcflurry/class1_allele_specific/class1_allele_specific_kmer_ic50_predictor_base.py", line 31, in <module>
    from ..ic50_predictor_base import IC50PredictorBase
  File "/home/alexander/anaconda3/lib/python3.5/site-packages/mhcflurry/ic50_predictor_base.py", line 24, in <module>
    from .dataset import Dataset
  File "/home/alexander/anaconda3/lib/python3.5/site-packages/mhcflurry/dataset.py", line 32, in <module>
    from .imputation_helpers import (
  File "/home/alexander/anaconda3/lib/python3.5/site-packages/mhcflurry/imputation_helpers.py", line 23, in <module>
    from fancyimpute.knn import KNN
  File "/home/alexander/anaconda3/lib/python3.5/site-packages/fancyimpute/__init__.py", line 4, in <module>
    from .nuclear_norm_minimization import NuclearNormMinimization
  File "/home/alexander/anaconda3/lib/python3.5/site-packages/fancyimpute/nuclear_norm_minimization.py", line 15, in <module>
    import cvxpy
  File "/home/alexander/anaconda3/lib/python3.5/site-packages/cvxpy/__init__.py", line 21, in <module>
    from cvxpy.atoms import *
  File "/home/alexander/anaconda3/lib/python3.5/site-packages/cvxpy/atoms/__init__.py", line 20, in <module>
    from cvxpy.atoms.affine_prod import affine_prod
  File "/home/alexander/anaconda3/lib/python3.5/site-packages/cvxpy/atoms/affine_prod.py", line 20, in <module>
    from cvxpy.atoms.atom import Atom
  File "/home/alexander/anaconda3/lib/python3.5/site-packages/cvxpy/atoms/atom.py", line 21, in <module>
    from .. import utilities as u
  File "/home/alexander/anaconda3/lib/python3.5/site-packages/cvxpy/utilities/__init__.py", line 24, in <module>
    from .quadratic import QuadCoeffExtractor
  File "/home/alexander/anaconda3/lib/python3.5/site-packages/cvxpy/utilities/quadratic.py", line 24, in <module>
    import canonInterface
  File "/home/alexander/anaconda3/lib/python3.5/site-packages/canonInterface.py", line 16, in <module>
    import CVXcanon
  File "/home/alexander/anaconda3/lib/python3.5/site-packages/CVXcanon.py", line 28, in <module>
    _CVXcanon = swig_import_helper()
  File "/home/alexander/anaconda3/lib/python3.5/site-packages/CVXcanon.py", line 24, in swig_import_helper
    _mod = imp.load_module('_CVXcanon', fp, pathname, description)
  File "/home/alexander/anaconda3/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/alexander/anaconda3/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /home/alexander/anaconda3/lib/python3.5/site-packages/_CVXcanon.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev

**Comment by alexanderwhatley** [comment]
I fixed this problem by downloading cvxpy using conda instead of pip. I guess the pip installation breaks somewhere.

**Comment by timodonnell** [comment]
From googling around this seems to be a linking problem related to compiler
versions, but I'm really not sure what the fix would be.

One idea: try "pip install --upgrade --force-reinstall --ignore-installed
 CVXcanon" to try reinstalling (and recompiling) the CVXcanon package.

If that doesn't work the maintainers of CVXcanon may have better ideas. If
you sort it out please let us know what the fix was.

**Comment by alexanderwhatley** [comment]
Yeah, I fixed this by downloading cvxpy separately. Will close.

**Comment by timodonnell** [comment]
Great, thanks. I added a note to the README about this.
